import pymysql
def view_data():
    conn = pymysql.connect(host="localhost",port=3306,db="studentsdb_diaz",user="root",password="")
    cursor = conn.cursor()
    sql = "SELECT * FROM students"
    cursor.execute(sql)
    result = cursor.fetchall()
    print(result)
    conn.close()
view_data()
def search():
    conn = pymysql.connect(host="localhost",port=3306,db="studentsdb_diaz",user="root",password="")
    cursor = conn.cursor()
    no=input("Enter a id")
    cursor.execute("SELECT * FROM STUDENTS WHERE ID LIKE %s","%"+no+"%")
    result = cursor.fetchall()
    print(result)
    conn.close()
search()
def insert():
    conn = pymysql.connect(host="localhost",port=3306,db="studentsdb_diaz",user="root",password="")
    cursor = conn.cursor()
    idNo=input('Enter id')
    fnames=input('Enter name')
    lnames=input('Enter last name')
    programs=input('Enter program')
    recordtuple=(idNo,fnames,lnames,programs)
    sql = """INSERT INTO students(id,fname,lname,program) VALUES (%s,%s,%s,%s)"""
    cursor.execute(sql,recordtuple)
    conn.commit()
    view_data()
insert() 
def delete():
    conn = pymysql.connect(host="localhost",port=3306,db="studentsdb_diaz",user="root",password="")
    cursor = conn.cursor()
    no=input("Enter a id")
    cursor.execute("DELETE FROM STUDENTS WHERE ID LIKE %s","%"+no+"%")
    conn.commit()
    conn.close()
    view_data()
delete()
def update():
    conn = pymysql.connect(host="localhost",port=3306,db="studentsdb_diaz",user="root",password="")
    cursor = conn.cursor()
    row=input('Enter row to be updated:')
    value=input("Enter a value:")
    row_update=input("Enter column will be referencing:")
    row_value=input("Enter a value of the row:")
    sql_update="""Update students set %s = %s where %s=%s"""
    cursor.execute(sql_update,row,value,row_update,row_value)
    result = cursor.fetchall()
    print(result)
    conn.close()
    view_data()
update()