# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TRANSACTION_WINDOW.ui'
#
# Created by: PyQt5 UI code generator 5.12
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
import pymysql
from PyQt5.QtGui import QPixmap
import sys
class Ui_Transactwin(object):
    def messagebox(self,title,message):
        mess=QtWidgets.QMessageBox()
        mess.setWindowIcon(QtGui.QIcon('App logo.png'))
        mess.setWindowTitle(title)
        mess.setText(message)
        mess.setStandardButtons(QtWidgets.QMessageBox.Ok|QtWidgets.QMessageBox.Cancel)
        mess.exec_()

    def confirmation(self,title,message):
        conn = pymysql.connect(host="localhost",port=3306,db="db_oragon",user="DBMS",password="12345")
        cursor = conn.cursor()
        conf=QtWidgets.QMessageBox()
        conf.setWindowIcon(QtGui.QIcon('App logo.png'))
        conf.setWindowTitle(title)
        conf.setText(message)
        conf.setStandardButtons(QtWidgets.QMessageBox.Ok|QtWidgets.QMessageBox.No)
        conf.exec_()
        if conf.Ok:
            conn.commit()
        elif conf.No:
            conn.rollback()
        conn.close()

    def addtransaction(self):
        try:
            name=self.NAME_LE.text()
            QTY=self.QTY_LE.text()
            conn = pymysql.connect(host="localhost",port=3306,db="db_oragon",user="DBMS",password="12345")
            cursor = conn.cursor()
            cursor.callproc('getQuantity',(name,QTY))
            result=cursor.fetchone()
            checker=result[0]

            if QTY ==0:
                self.messagebox('Error','Enter a value')
                self.NAME_LE.clear()
                self.QTY_LE.clear()

            elif checker >=QTY:
                cursor.callproc('Minus_QTY',(name,QTY))
                self.confirmation('Confirm','Do you want to add this?')
            else:
                self.messagebox('Error','Product is out of stock')
                self.NAME_LE.clear()
                self.QTY_LE.clear()
        except:
            self.messagebox('Error','Enter value')

    def addTable(self,columns):
        rowPosition=self.tableWidget.rowCount()
        self.tableWidget.insertRow(rowPosition)
        for i, column in enumerate(columns):
                self.tableWidget.setItem(rowPosition,i, QtWidgets.QTableWidgetItem(str(column)))
    def viewtransact(self):
        conn = pymysql.connect(host="localhost",port=3306,db="db_oragon",user="DBMS",password="12345")
        cursor = conn.cursor()
        cursor.callproc('getorder')
        result = cursor.fetchall()
        self.tableWidget.setRowCount(0)
        for row in result:
                self.addTable(row)
                cursor.close()
    def setupUi(self, Transacrwin):
        Transacrwin.setObjectName("Transacrwin")
        Transacrwin.resize(853, 655)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Transacrwin.sizePolicy().hasHeightForWidth())
        Transacrwin.setSizePolicy(sizePolicy)
        Transacrwin.setMinimumSize(QtCore.QSize(853, 655))
        Transacrwin.setMaximumSize(QtCore.QSize(853, 655))
        Transacrwin.setSizeIncrement(QtCore.QSize(853, 655))
        Transacrwin.setBaseSize(QtCore.QSize(853, 655))
        self.centralwidget = QtWidgets.QWidget(Transacrwin)
        self.centralwidget.setObjectName("centralwidget")
        self.Background = QtWidgets.QLabel(self.centralwidget)
        self.Background.setGeometry(QtCore.QRect(0, 0, 853, 655))
        self.Background.setPixmap(QPixmap('Wallpaper_TRANSACTIONWINDOW.png'))
        self.Background.setText("")
        self.Background.setObjectName("Background")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(250, 70, 590, 580))
        self.tableWidget.setFrameShape(QtWidgets.QFrame.Box)
        self.tableWidget.setDragDropOverwriteMode(False)
        self.tableWidget.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.tableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectItems)
        self.tableWidget.setShowGrid(True)
        self.tableWidget.setGridStyle(QtCore.Qt.CustomDashLine)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(7)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        self.tableWidget.horizontalHeader().setVisible(True)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(90)
        self.tableWidget.horizontalHeader().setHighlightSections(True)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(100)
        self.tableWidget.horizontalHeader().setSortIndicatorShown(False)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.tableWidget.verticalHeader().setVisible(True)
        self.tableWidget.verticalHeader().setCascadingSectionResizes(False)
        self.tableWidget.verticalHeader().setDefaultSectionSize(30)
        self.tableWidget.verticalHeader().setHighlightSections(True)
        self.tableWidget.verticalHeader().setSortIndicatorShown(False)
        self.tableWidget.verticalHeader().setStretchLastSection(False)
        self.SUBMIT = QtWidgets.QPushButton(self.centralwidget)
        self.SUBMIT.setGeometry(QtCore.QRect(30, 310, 191, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.SUBMIT.setFont(font)
        self.SUBMIT.setObjectName("SUBMIT")
        self.SUBMIT.clicked.connect(self.addtransaction)
        self.NAME_LE = QtWidgets.QLineEdit(self.centralwidget)
        self.NAME_LE.setGeometry(QtCore.QRect(30, 120, 191, 51))
        self.NAME_LE.setText("")
        self.NAME_LE.setObjectName("NAME_LE")
        self.QTY_LE = QtWidgets.QLineEdit(self.centralwidget)
        self.QTY_LE.setGeometry(QtCore.QRect(30, 230, 191, 51))
        self.QTY_LE.setObjectName("QTY_LE")
        self.NAME_LABEL = QtWidgets.QLabel(self.centralwidget)
        self.NAME_LABEL.setGeometry(QtCore.QRect(30, 70, 191, 41))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.NAME_LABEL.setFont(font)
        self.NAME_LABEL.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.NAME_LABEL.setObjectName("NAME_LABEL")
        self.QTY_LABEL = QtWidgets.QLabel(self.centralwidget)
        self.QTY_LABEL.setGeometry(QtCore.QRect(30, 180, 191, 41))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.QTY_LABEL.setFont(font)
        self.QTY_LABEL.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.QTY_LABEL.setObjectName("QTY_LABEL")
        self.RECEIPT_LABEL = QtWidgets.QLabel(self.centralwidget)
        self.RECEIPT_LABEL.setGeometry(QtCore.QRect(10, 430, 241, 211))
        self.RECEIPT_LABEL.setStyleSheet("background-color: transparent; color: LawnGreen;")
        self.RECEIPT_LABEL.setText("Total Price:")
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.RECEIPT_LABEL.setFont(font)
        self.RECEIPT_LABEL.setObjectName("RECEIPT_LABEL")
        self.BOR_LINE1 = QtWidgets.QFrame(self.centralwidget)
        self.BOR_LINE1.setGeometry(QtCore.QRect(0, 50, 851, 20))
        self.BOR_LINE1.setStyleSheet("color: rgb(0, 0, 0);")
        self.BOR_LINE1.setFrameShape(QtWidgets.QFrame.HLine)
        self.BOR_LINE1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.BOR_LINE1.setObjectName("BOR_LINE1")
        self.TRANSACTIONPAGE = QtWidgets.QLabel(self.centralwidget)
        self.TRANSACTIONPAGE.setGeometry(QtCore.QRect(290, 10, 321, 41))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.TRANSACTIONPAGE.setFont(font)
        self.TRANSACTIONPAGE.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.TRANSACTIONPAGE.setObjectName("TRANSACTIONPAGE")
        self.BOR_LINE2 = QtWidgets.QFrame(self.centralwidget)
        self.BOR_LINE2.setGeometry(QtCore.QRect(0, 20, 291, 20))
        self.BOR_LINE2.setStyleSheet("color: rgb(0, 0, 0);")
        self.BOR_LINE2.setFrameShape(QtWidgets.QFrame.HLine)
        self.BOR_LINE2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.BOR_LINE2.setObjectName("BOR_LINE2")
        self.BOR_LINE3 = QtWidgets.QFrame(self.centralwidget)
        self.BOR_LINE3.setGeometry(QtCore.QRect(550, 20, 301, 20))
        self.BOR_LINE3.setStyleSheet("color: qconicalgradient(cx:0.5, cy:0.5, angle:0, stop:0 rgba(255, 255, 255, 255), stop:0.373979 rgba(255, 255, 255, 255), stop:0.373991 rgba(33, 30, 255, 255), stop:0.624018 rgba(33, 30, 255, 255), stop:0.624043 rgba(255, 0, 0, 255), stop:1 rgba(255, 0, 0, 255));")
        self.BOR_LINE3.setFrameShape(QtWidgets.QFrame.HLine)
        self.BOR_LINE3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.BOR_LINE3.setObjectName("BOR_LINE3")
        self.viewtrans = QtWidgets.QPushButton(self.centralwidget)
        self.viewtrans.setGeometry(QtCore.QRect(30, 370, 191, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.viewtrans.setFont(font)
        self.viewtrans.setObjectName("viewtrans")
        Transacrwin.setCentralWidget(self.centralwidget)

        self.retranslateUi(Transacrwin)
        QtCore.QMetaObject.connectSlotsByName(Transacrwin)

    def retranslateUi(self, Transacrwin):
        _translate = QtCore.QCoreApplication.translate
        Transacrwin.setWindowTitle(_translate("Transacrwin", "Transaction"))
        self.SUBMIT.setText(_translate("Transacrwin", "Submit"))
        self.NAME_LABEL.setText(_translate("Transacrwin", "Name:"))
        self.QTY_LABEL.setText(_translate("Transacrwin", "Quantity:"))
        self.TRANSACTIONPAGE.setText(_translate("Transacrwin", "TRANSACTION PAGE"))
        self.viewtrans.setText(_translate("Transacrwin", "View All Transaction"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Transacrwin", "Order ID"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Transacrwin", "Customer ID"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Transacrwin", "Admin ID"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Transacrwin", "Product Name"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Transacrwin", "Product Quantity"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("Transacrwin", "Total Price"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("Transacrwin", "Date of Transaction"))

if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_Transactwin()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())