# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TRANSACTION_WINDOW.ui'
#
# Created by: PyQt5 UI code generator 5.12
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
import pymysql
from PyQt5.QtGui import QPixmap
import sys
import datetime
class Ui_Transactwin(object):
    def messagebox(self,title,message):
        mess=QtWidgets.QMessageBox()
        mess.setWindowIcon(QtGui.QIcon('App logo.png'))
        mess.setWindowTitle(title)
        mess.setText(message)
        mess.setStandardButtons(QtWidgets.QMessageBox.Ok|QtWidgets.QMessageBox.Cancel)
        mess.exec_()
    def confirmation(self,title,message):
        mess=QtWidgets.QMessageBox()
        mess.setWindowIcon(QtGui.QIcon('App logo.png'))
        mess.setWindowTitle(title)
        mess.setText(message)
        mess.setStandardButtons(QtWidgets.QMessageBox.Ok|QtWidgets.QMessageBox.No)
        mess.exec_()
    def addtransaction(self):
        currentDT = datetime.datetime.now()
        name=str(self.NAME_LE.text())
        QTY=int(self.QTY_LE.text())
        print(QTY)
        Customer=self.Customer_name.text()
        conn = pymysql.connect(host="localhost",port=3306,db="dboragon",user="DBMS",password="12345")
        cursor = conn.cursor()
        cursor.execute('select Prod_QTY, Prod_Price from SALES_Product where Prod_Name=%s',name)
        result=cursor.fetchone()
        checker=int(result[0])
        total=int(result[1])
        total=total*QTY

        if QTY ==0:
            self.messagebox('Error','Enter a value')
            self.NAME_LE.clear()
            self.Customer_name.clear()
            self.QTY_LE.clear()

        elif checker >= QTY:
            cursor.execute('insert into sales_customerinfo (Customer_Name) values (%s)',(Customer))
            cursor.execute('update sales_product set Prod_QTY= Prod_QTY-\'{0}\' where Prod_Name= \'{1}\''.format(QTY,name))
            cursor.execute('select Customer_ID from sales_customerinfo')
            result=cursor.fetchone()
            customerid=result[0]
            cursor.execute('select Admin_ID from admin_info')
            adminres=cursor.fetchone()
            admin_id=adminres[0]
            cursor.execute('Select Prod_Name from sales_product where Prod_Name=%s',name)
            product=cursor.fetchone()
            product_name=product[0]
            cursor.execute('insert into sales_order (Customer_ID, Admin_ID,Prod_Name, Prod_Qty, Total_Price, Transaction_Date) values (%s,%s,%s,%s,%s,%s)',
            (customerid,admin_id,product_name,QTY,total,currentDT))
            conn.commit()
            self.RECEIPT_LABEL.setText("Total Price: %d" %total)

        else:
            self.NAME_LE.clear()
            self.QTY_LE.clear()

    def addTable(self,columns):
        rowPosition=self.tableWidget.rowCount()
        self.tableWidget.insertRow(rowPosition)
        for i, column in enumerate(columns):
                self.tableWidget.setItem(rowPosition,i, QtWidgets.QTableWidgetItem(str(column)))

    def viewtransact(self):
        conn = pymysql.connect(host="localhost",port=3306,db="dboragon",user="DBMS",password="12345")
        cursor = conn.cursor()
        cursor.callproc('getorder')
        result = cursor.fetchall()
        self.tableWidget.setRowCount(0)
        for row in result:
                self.addTable(row)
                cursor.close()

    def setupUi(self, Transacrwin):
        Transacrwin.setObjectName("Transacrwin")
        Transacrwin.resize(853, 655)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Transacrwin.sizePolicy().hasHeightForWidth())
        Transacrwin.setSizePolicy(sizePolicy)
        Transacrwin.setMinimumSize(QtCore.QSize(853, 655))
        Transacrwin.setMaximumSize(QtCore.QSize(853, 655))
        Transacrwin.setSizeIncrement(QtCore.QSize(853, 655))
        Transacrwin.setBaseSize(QtCore.QSize(853, 655))
        self.centralwidget = QtWidgets.QWidget(Transacrwin)
        self.centralwidget.setObjectName("centralwidget")
        self.Background = QtWidgets.QLabel(self.centralwidget)
        self.Background.setGeometry(QtCore.QRect(0, 0, 853, 655))
        self.Background.setPixmap(QPixmap('Wallpaper_TRANSACTIONWINDOW.png'))
        self.Background.setObjectName("Background")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(260, 190, 571, 421))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(7)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        self.tableWidget.horizontalHeader().setVisible(True)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(90)
        self.tableWidget.horizontalHeader().setHighlightSections(True)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(100)
        self.tableWidget.horizontalHeader().setSortIndicatorShown(False)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.tableWidget.verticalHeader().setVisible(True)
        self.tableWidget.verticalHeader().setCascadingSectionResizes(False)
        self.tableWidget.verticalHeader().setDefaultSectionSize(30)
        self.tableWidget.verticalHeader().setHighlightSections(True)
        self.tableWidget.verticalHeader().setSortIndicatorShown(False)
        self.tableWidget.verticalHeader().setStretchLastSection(False)
        self.SUBMIT = QtWidgets.QPushButton(self.centralwidget)
        self.SUBMIT.setGeometry(QtCore.QRect(30, 310, 191, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.SUBMIT.setFont(font)
        self.SUBMIT.setObjectName("SUBMIT")
        self.SUBMIT.clicked.connect(self.addtransaction)
        self.NAME_LE = QtWidgets.QLineEdit(self.centralwidget)
        self.NAME_LE.setGeometry(QtCore.QRect(30, 120, 191, 51))
        self.NAME_LE.setText("")
        self.NAME_LE.setObjectName("NAME_LE")
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.NAME_LE.setFont(font)
        self.QTY_LE = QtWidgets.QLineEdit(self.centralwidget)
        self.QTY_LE.setGeometry(QtCore.QRect(30, 230, 191, 51))
        self.QTY_LE.setObjectName("QTY_LE")
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.QTY_LE.setFont(font)
        self.NAME_LABEL = QtWidgets.QLabel(self.centralwidget)
        self.NAME_LABEL.setGeometry(QtCore.QRect(30, 70, 191, 41))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.NAME_LABEL.setFont(font)
        self.NAME_LABEL.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.NAME_LABEL.setObjectName("NAME_LABEL")
        self.QTY_LABEL = QtWidgets.QLabel(self.centralwidget)
        self.QTY_LABEL.setGeometry(QtCore.QRect(30, 180, 191, 41))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.QTY_LABEL.setFont(font)
        self.QTY_LABEL.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.QTY_LABEL.setObjectName("QTY_LABEL")
        self.RECEIPT_LABEL = QtWidgets.QLabel(self.centralwidget)
        self.RECEIPT_LABEL.setGeometry(QtCore.QRect(10, 430, 241, 211))
        self.RECEIPT_LABEL.setStyleSheet("background-color: transparent; color: LawnGreen;")
        self.RECEIPT_LABEL.setObjectName("RECEIPT_LABEL")
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.RECEIPT_LABEL.setFont(font)
        self.BOR_LINE1 = QtWidgets.QFrame(self.centralwidget)
        self.BOR_LINE1.setGeometry(QtCore.QRect(0, 50, 851, 20))
        self.BOR_LINE1.setStyleSheet("color: rgb(0, 0, 0);")
        self.BOR_LINE1.setFrameShape(QtWidgets.QFrame.HLine)
        self.BOR_LINE1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.BOR_LINE1.setObjectName("BOR_LINE1")
        self.TRANSACTIONPAGE = QtWidgets.QLabel(self.centralwidget)
        self.TRANSACTIONPAGE.setGeometry(QtCore.QRect(290, 10, 321, 41))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.TRANSACTIONPAGE.setFont(font)
        self.TRANSACTIONPAGE.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.TRANSACTIONPAGE.setObjectName("TRANSACTIONPAGE")
        self.BOR_LINE2 = QtWidgets.QFrame(self.centralwidget)
        self.BOR_LINE2.setGeometry(QtCore.QRect(0, 20, 291, 20))
        self.BOR_LINE2.setStyleSheet("color: rgb(0, 0, 0);")
        self.BOR_LINE2.setFrameShape(QtWidgets.QFrame.HLine)
        self.BOR_LINE2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.BOR_LINE2.setObjectName("BOR_LINE2")
        self.BOR_LINE3 = QtWidgets.QFrame(self.centralwidget)
        self.BOR_LINE3.setGeometry(QtCore.QRect(550, 20, 301, 20))
        self.BOR_LINE3.setStyleSheet("color: qconicalgradient(cx:0.5, cy:0.5, angle:0, stop:0 rgba(255, 255, 255, 255), stop:0.373979 rgba(255, 255, 255, 255), stop:0.373991 rgba(33, 30, 255, 255), stop:0.624018 rgba(33, 30, 255, 255), stop:0.624043 rgba(255, 0, 0, 255), stop:1 rgba(255, 0, 0, 255));")
        self.BOR_LINE3.setFrameShape(QtWidgets.QFrame.HLine)
        self.BOR_LINE3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.BOR_LINE3.setObjectName("BOR_LINE3")
        self.viewtrans = QtWidgets.QPushButton(self.centralwidget)
        self.viewtrans.setGeometry(QtCore.QRect(30, 370, 191, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.viewtrans.setFont(font)
        self.viewtrans.setObjectName("viewtrans")
        self.viewtrans.clicked.connect(self.viewtransact)
        self.NAME_LABEL_2 = QtWidgets.QLabel(self.centralwidget)
        self.NAME_LABEL_2.setGeometry(QtCore.QRect(270, 70, 211, 41))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.NAME_LABEL_2.setFont(font)
        self.NAME_LABEL_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.NAME_LABEL_2.setObjectName("NAME_LABEL_2")
        self.Customer_name = QtWidgets.QLineEdit(self.centralwidget)
        self.Customer_name.setGeometry(QtCore.QRect(280, 120, 551, 51))
        self.Customer_name.setText("")
        self.Customer_name.setObjectName("Customer_name")
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.Customer_name.setFont(font)
        Transacrwin.setCentralWidget(self.centralwidget)

        self.retranslateUi(Transacrwin)
        QtCore.QMetaObject.connectSlotsByName(Transacrwin)

    def retranslateUi(self, Transacrwin):
        _translate = QtCore.QCoreApplication.translate
        Transacrwin.setWindowTitle(_translate("Transacrwin", "Transaction"))
        self.SUBMIT.setText(_translate("Transacrwin", "Submit"))
        self.NAME_LABEL.setText(_translate("Transacrwin", "Name:"))
        self.QTY_LABEL.setText(_translate("Transacrwin", "Quantity:"))
        self.TRANSACTIONPAGE.setText(_translate("Transacrwin", "TRANSACTION PAGE"))
        self.viewtrans.setText(_translate("Transacrwin", "View All Transaction"))
        self.NAME_LABEL_2.setText(_translate("Transacrwin", "Customer Name:"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Transacrwin", "Order ID"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Transacrwin", "Customer ID"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Transacrwin", "Admin ID"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Transacrwin", "Product Name"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Transacrwin", "Product Quantity"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("Transacrwin", "Total Price"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("Transacrwin", "Date of Transaction"))

if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_Transactwin()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

